"""Provider-neutral domain contracts for the self-service cloud platform."""

from .adapters import (
    AWSProviderAdapter,
    AzureProviderAdapter,
    ProviderAdapter,
)
from .errors import (
    AdapterProviderMismatchError,
    DomainError,
    InstallationConfigurationError,
    InvalidLifecycleTransitionError,
    MissingProviderAdapterError,
    ProviderLockedError,
)
from .models import (
    CloudProvider,
    ClusterSize,
    DataClassification,
    EnvironmentRequest,
    EnvironmentType,
    InstallationGuardrails,
    InstallationMode,
    InstallationProfile,
    InstallationStatus,
    PolicyDecision,
    PolicyViolation,
    ProviderValidation,
    ResolvedEnvironmentRequest,
    SimulationOutcome,
    SimulationResource,
    SimulationResult,
)
from .normalization import normalize_request
from .orchestrator import SimulationOrchestrator
from .policies import evaluate_common_policies, merge_decisions
from .proposals import (
    BUNDLE_MARKER_FILENAME,
    PROPOSAL_SCHEMA_VERSION,
    DeploymentProposal,
    ProposalArtifact,
    ProposalBundleMarker,
    ProposalInputError,
    ProposalState,
    build_deployment_proposal,
)

__all__ = [
    "AWSProviderAdapter",
    "AdapterProviderMismatchError",
    "AzureProviderAdapter",
    "BUNDLE_MARKER_FILENAME",
    "CloudProvider",
    "ClusterSize",
    "DataClassification",
    "DeploymentProposal",
    "DomainError",
    "EnvironmentRequest",
    "EnvironmentType",
    "InstallationConfigurationError",
    "InstallationGuardrails",
    "InstallationMode",
    "InstallationProfile",
    "InstallationStatus",
    "InvalidLifecycleTransitionError",
    "MissingProviderAdapterError",
    "PolicyDecision",
    "PolicyViolation",
    "PROPOSAL_SCHEMA_VERSION",
    "ProviderAdapter",
    "ProviderLockedError",
    "ProviderValidation",
    "ProposalArtifact",
    "ProposalBundleMarker",
    "ProposalInputError",
    "ProposalState",
    "ResolvedEnvironmentRequest",
    "SimulationOrchestrator",
    "SimulationOutcome",
    "SimulationResource",
    "SimulationResult",
    "build_deployment_proposal",
    "evaluate_common_policies",
    "merge_decisions",
    "normalize_request",
]
