/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployment-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deployment Proposals */
        get: operations["list_deployment_proposals_v1_deployment_proposals_get"];
        put?: never;
        /** Create Deployment Proposal */
        post: operations["create_deployment_proposal_v1_deployment_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deployment-proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deployment Proposal */
        get: operations["get_deployment_proposal_v1_deployment_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/environment-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Environment Requests */
        get: operations["list_environment_requests_v1_environment_requests_get"];
        put?: never;
        /** Create Environment Request */
        post: operations["create_environment_request_v1_environment_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/environment-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Environment Request */
        get: operations["get_environment_request_v1_environment_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/installation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Installation */
        get: operations["get_installation_v1_platform_installation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/installation/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Installation */
        post: operations["validate_installation_v1_platform_installation_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/installations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Installation */
        post: operations["create_installation_v1_platform_installations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Modes */
        get: operations["modes_v1_platform_modes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_v1_platform_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Version */
        get: operations["app_version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CloudProvider
         * @enum {string}
         */
        CloudProvider: "aws" | "azure";
        /**
         * ClusterSize
         * @enum {string}
         */
        ClusterSize: "small" | "medium" | "large";
        /**
         * DataClassification
         * @enum {string}
         */
        DataClassification: "public" | "internal" | "confidential" | "restricted";
        /**
         * DeploymentProposal
         * @description Immutable proposal metadata and its complete textual artifact bundle.
         */
        DeploymentProposal: {
            /** Artifacts */
            artifacts: components["schemas"]["ProposalArtifact"][];
            /** Content Hash */
            content_hash: string;
            /** Installation Id */
            installation_id: string;
            mode: components["schemas"]["InstallationMode"];
            /** Proposal Id */
            proposal_id: string;
            provider: components["schemas"]["CloudProvider"];
            /** Request Fingerprint */
            request_fingerprint: string;
            /** Request Id */
            request_id: string;
            /**
             * Schema Version
             * @default proposal.v1
             */
            schema_version: string;
            /** @default ready_for_review */
            state: components["schemas"]["ProposalState"];
        };
        /**
         * EnvironmentRequest
         * @description Raw request submitted by a user; deliberately contains no provider.
         */
        EnvironmentRequest: {
            /** Application */
            application: string;
            /** Business Justification */
            business_justification: string;
            cluster_size: components["schemas"]["ClusterSize"];
            /** Cost Centre */
            cost_centre: string;
            data_classification: components["schemas"]["DataClassification"];
            environment: components["schemas"]["EnvironmentType"];
            /** Monthly Budget */
            monthly_budget: number | string;
            /**
             * Network Cidr
             * Format: ipvanynetwork
             */
            network_cidr: string;
            /** Non Production Expiry */
            non_production_expiry?: string | null;
            /** Owner */
            owner: string;
            /** Region */
            region: string;
        };
        /** EnvironmentRequestRecord */
        EnvironmentRequestRecord: {
            /** Idempotency Key */
            idempotency_key: string;
            outcome: components["schemas"]["SimulationOutcome"];
            request: components["schemas"]["ResolvedEnvironmentRequest"];
            /** State */
            state: string;
        };
        /**
         * EnvironmentType
         * @enum {string}
         */
        EnvironmentType: "development" | "test" | "production";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstallationCreateBody */
        InstallationCreateBody: {
            guardrails?: components["schemas"]["InstallationGuardrails-Input"] | null;
            /**
             * Installation Id
             * @default default
             */
            installation_id: string;
            /** @default simulation */
            mode: components["schemas"]["InstallationMode"];
            provider: components["schemas"]["CloudProvider"];
        };
        /**
         * InstallationGuardrails
         * @description Common limits applied before a provider adapter is consulted.
         */
        "InstallationGuardrails-Input": {
            /**
             * Allowed Cluster Sizes
             * @default [
             *       "small",
             *       "medium",
             *       "large"
             *     ]
             */
            allowed_cluster_sizes: components["schemas"]["ClusterSize"][];
            /**
             * Allowed Regions
             * @default [
             *       "example-region"
             *     ]
             */
            allowed_regions: string[];
            /**
             * Budget Maximum
             * @default 1000.00
             */
            budget_maximum: number | string;
            /**
             * Max Nonproduction Lifetime Days
             * @default 30
             */
            max_nonproduction_lifetime_days: number;
        };
        /**
         * InstallationGuardrails
         * @description Common limits applied before a provider adapter is consulted.
         */
        "InstallationGuardrails-Output": {
            /**
             * Allowed Cluster Sizes
             * @default [
             *       "small",
             *       "medium",
             *       "large"
             *     ]
             */
            allowed_cluster_sizes: components["schemas"]["ClusterSize"][];
            /**
             * Allowed Regions
             * @default [
             *       "example-region"
             *     ]
             */
            allowed_regions: string[];
            /**
             * Budget Maximum
             * @default 1000.00
             */
            budget_maximum: string;
            /**
             * Max Nonproduction Lifetime Days
             * @default 30
             */
            max_nonproduction_lifetime_days: number;
        };
        /**
         * InstallationMode
         * @enum {string}
         */
        InstallationMode: "simulation" | "sandbox" | "enterprise";
        /**
         * InstallationProfile
         * @description Provider and lifecycle configuration for one installation.
         */
        InstallationProfile: {
            guardrails?: components["schemas"]["InstallationGuardrails-Output"];
            /** Installation Id */
            installation_id: string;
            /** @default simulation */
            mode: components["schemas"]["InstallationMode"];
            provider?: components["schemas"]["CloudProvider"] | null;
            /** @default draft */
            status: components["schemas"]["InstallationStatus"];
        };
        /** InstallationResponse */
        InstallationResponse: {
            installation: components["schemas"]["InstallationProfile"];
            validation?: components["schemas"]["InstallationValidation"] | null;
        };
        /**
         * InstallationStatus
         * @enum {string}
         */
        InstallationStatus: "draft" | "active" | "retired";
        /** InstallationValidation */
        InstallationValidation: {
            /** Allowed */
            allowed: boolean;
            /**
             * Violations
             * @default []
             */
            violations: components["schemas"]["PolicyViolation"][];
        };
        /** ModeDescriptor */
        ModeDescriptor: {
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /** Execution */
            execution: string;
            mode: components["schemas"]["InstallationMode"];
        };
        /** ModeListResponse */
        ModeListResponse: {
            /** Modes */
            modes: components["schemas"]["ModeDescriptor"][];
        };
        /**
         * PolicyDecision
         * @description Deterministic aggregate policy result.
         */
        PolicyDecision: {
            /** Allowed */
            allowed: boolean;
            /**
             * Violations
             * @default []
             */
            violations: components["schemas"]["PolicyViolation"][];
        };
        /**
         * PolicyViolation
         * @description Stable, user-facing explanation of one failed policy.
         */
        PolicyViolation: {
            /** Code */
            code: string;
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /**
         * ProposalArtifact
         * @description One textual file in a proposal bundle.
         */
        ProposalArtifact: {
            /** Content */
            content: string;
            /** Relative Path */
            relative_path: string;
        };
        /** ProposalCreateBody */
        ProposalCreateBody: {
            /** Request Id */
            request_id: string;
        };
        /** ProposalListResponse */
        ProposalListResponse: {
            /** Proposals */
            proposals: components["schemas"]["DeploymentProposal"][];
        };
        /**
         * ProposalState
         * @description The only truthful state the local, review-only service can claim.
         * @enum {string}
         */
        ProposalState: "ready_for_review";
        /** ProviderDescriptor */
        ProviderDescriptor: {
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            provider: components["schemas"]["CloudProvider"];
        };
        /** ProviderListResponse */
        ProviderListResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderDescriptor"][];
        };
        /** RequestListResponse */
        RequestListResponse: {
            /** Requests */
            requests: components["schemas"]["EnvironmentRequestRecord"][];
        };
        /**
         * ResolvedEnvironmentRequest
         * @description Normalized request with the provider resolved from the profile.
         */
        ResolvedEnvironmentRequest: {
            /** Application */
            application: string;
            /** Business Justification */
            business_justification: string;
            /** Canonical Json */
            canonical_json: string;
            cluster_size: components["schemas"]["ClusterSize"];
            /** Cost Centre */
            cost_centre: string;
            data_classification: components["schemas"]["DataClassification"];
            environment: components["schemas"]["EnvironmentType"];
            /** Fingerprint */
            fingerprint: string;
            /** Monthly Budget */
            monthly_budget: string;
            /**
             * Network Cidr
             * Format: ipvanynetwork
             */
            network_cidr: string;
            /** Non Production Expiry */
            non_production_expiry?: string | null;
            /** Owner */
            owner: string;
            provider: components["schemas"]["CloudProvider"];
            /** Region */
            region: string;
            /** Request Id */
            request_id: string;
        };
        /**
         * SimulationOutcome
         * @description Policy decision plus optional deterministic simulation result.
         */
        SimulationOutcome: {
            decision: components["schemas"]["PolicyDecision"];
            result?: components["schemas"]["SimulationResult"] | null;
        };
        /**
         * SimulationResource
         * @description Stable description of a resource that would be proposed.
         */
        SimulationResource: {
            /**
             * Attributes
             * @default []
             */
            attributes: [
                string,
                string
            ][];
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /**
         * SimulationResult
         * @description Credential-free simulation output.
         */
        SimulationResult: {
            /** Fingerprint */
            fingerprint: string;
            provider: components["schemas"]["CloudProvider"];
            /** Request Id */
            request_id: string;
            /** Resources */
            resources: components["schemas"]["SimulationResource"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    list_deployment_proposals_v1_deployment_proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalListResponse"];
                };
            };
        };
    };
    create_deployment_proposal_v1_deployment_proposals_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deployment_proposal_v1_deployment_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_environment_requests_v1_environment_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestListResponse"];
                };
            };
        };
    };
    create_environment_request_v1_environment_requests_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentRequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_environment_request_v1_environment_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentRequestRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_installation_v1_platform_installation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationProfile"];
                };
            };
        };
    };
    validate_installation_v1_platform_installation_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationValidation"];
                };
            };
        };
    };
    create_installation_v1_platform_installations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallationCreateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modes_v1_platform_modes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeListResponse"];
                };
            };
        };
    };
    providers_v1_platform_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListResponse"];
                };
            };
        };
    };
    app_version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
