apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "platform.fullname" . }}-api
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      {{- include "platform.apiSelector" . | nindent 6 }}
