apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform.fullname" . }}-portal
  labels:
    {{- include "platform.portalSelector" . | nindent 4 }}
spec:
  replicas: {{ .Values.portal.replicaCount }}
  selector:
    matchLabels:
      {{- include "platform.portalSelector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "platform.portalSelector" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "platform.fullname" . }}-portal
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  {{- include "platform.portalSelector" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "platform.portalSelector" . | nindent 14 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: portal
          image: "{{ .Values.portal.image.repository }}:{{ .Values.portal.image.tag }}"
          imagePullPolicy: {{ .Values.portal.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.portal.service.port }}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-tmp
              mountPath: /tmp/nginx
          resources:
            {{- toYaml .Values.portal.resources | nindent 12 }}
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
