apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform.fullname" . }}-api
  labels:
    {{- include "platform.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.api.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform.fullname" . }}-portal
  labels:
    {{- include "platform.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.portal.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
